### ISSUE TITLE
Add --force-generate-all flag; include it as a GH action

### ISSUE THREAD

**Issue by wesslen** [wesslen/bayesian-beagle#10]
As a GH action:

```
on:
  workflow_dispatch:
    inputs:
      force_generate_all:
        description: 'Force generate all posts'
        required: false
        type: boolean
        default: false

      - name: Run script
        run: python generate_posts.py --force_generate_all ${{ github.event.inputs.force_generate_all }}
```
